// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RealizarbuscaatravsdomenuTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void acessarSite() {
    driver.get("https://www.submarino.com.br/produto/93842005/xiaomi-redmi-airdots-fone-de-ouvido-5-0-fones-de-ouvido-sem-fio-com-microfone-handsfree-f?pfm_carac=Fones%20de%20Ouvido&pfm_page=category&pfm_pos=grid&pfm_type=vit_product_grid/");
    driver.manage().window().setSize(new Dimension(1050, 708));
    driver.findElement(By.cssSelector(".ColUI-gjy0oc-0 > .spacey-image .Image-sc-1m5klhe-0")).click();
  }
  @Test
  public void realizarbuscapelomenu() {
    driver.get("https://www.submarino.com.br/landingpage/gamer-hardcore?chave=prf_hm_hr_0_1_gamer-hardcore-header&pfmPage=home&pfmPos=maintop1&pfm_carac=Nome%20da%20area&pfm_index=0&pfm_type=vit_spacey");
    driver.manage().window().setSize(new Dimension(1050, 708));
    {
      WebElement element = driver.findElement(By.linkText("Vem ver as lojasAbrir menu"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".mmn-sdb-arrow:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".mmn-sdb-arrow:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".mmn-sdb-arrow:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("Vem ver as lojasAbrir menu"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.get("https://www.submarino.com.br/categoria/audio/fones-de-ouvido");
  }
  @Test
  public void selecionarProdutoatravsdomenu() {
    driver.get("https://www.submarino.com.br/categoria/audio/fones-de-ouvido");
    driver.manage().window().setSize(new Dimension(1050, 708));
    js.executeScript("window.scrollTo(0,200)");
    js.executeScript("window.scrollTo(0,400)");
    driver.findElement(By.cssSelector(".row:nth-child(1) > .product-grid-item:nth-child(1) .PriceUI-bwhjk3-11:nth-child(1)")).click();
  }
  @Test
  public void adicionarnovofoneaoCarrinho() {
    driver.get("https://www.submarino.com.br/produto/93842005/xiaomi-redmi-airdots-fone-de-ouvido-5-0-fones-de-ouvido-sem-fio-com-microfone-handsfree-f?pfm_carac=Fones%20de%20Ouvido&pfm_page=category&pfm_pos=grid&pfm_type=vit_product_grid");
    driver.manage().window().setSize(new Dimension(1050, 708));
    driver.findElement(By.cssSelector(".bmDUpk")).click();
  }
}
