// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RealizarbuscapelalinhadigitvelTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void acessarSite() {
    driver.get("https://www.submarino.com.br/produto/93842005/xiaomi-redmi-airdots-fone-de-ouvido-5-0-fones-de-ouvido-sem-fio-com-microfone-handsfree-f?pfm_carac=Fones%20de%20Ouvido&pfm_page=category&pfm_pos=grid&pfm_type=vit_product_grid/");
    driver.manage().window().setSize(new Dimension(1050, 708));
    driver.findElement(By.cssSelector(".ColUI-gjy0oc-0 > .spacey-image .Image-sc-1m5klhe-0")).click();
  }
  @Test
  public void realizarBusca() {
    driver.get("https://www.submarino.com.br/landingpage/gamer-hardcore?chave=prf_hm_hr_0_1_gamer-hardcore-header&pfmPage=home&pfmPos=maintop1&pfm_carac=Nome%20da%20area&pfm_index=0&pfm_type=vit_spacey");
    driver.manage().window().setSize(new Dimension(1050, 708));
    driver.findElement(By.id("h_search-input")).click();
    driver.findElement(By.id("h_search-input")).sendKeys("fone de ouvido");
    driver.findElement(By.id("h_search-btn")).click();
  }
  @Test
  public void selecionarProduto() {
    driver.get("https://www.submarino.com.br/busca/fone-de-ouvido");
    js.executeScript("window.scrollTo(0,584)");
    driver.findElement(By.cssSelector(".product-grid-item:nth-child(2) .TitleUI-bwhjk3-15")).click();
    driver.manage().window().setSize(new Dimension(1050, 708));
  }
  @Test
  public void adicionaraoCarrinho() {
    driver.get("https://www.submarino.com.br/produto/93842005/xiaomi-redmi-airdots-fone-de-ouvido-5-0-fones-de-ouvido-sem-fio-com-microfone-handsfree-f?pfm_carac=fone%20de%20ouvido&pfm_index=1&pfm_page=search&pfm_pos=grid&pfm_type=search_page");
    driver.manage().window().setSize(new Dimension(1050, 708));
    driver.findElement(By.cssSelector(".bmDUpk")).click();
  }
}
